
name: testing repo
run-name: ${{github.actor}} is trying to do a pull request
on: [pull_request]
jobs: 
  test-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make check
